library(shiny)
library(DT)
m = matrix(c(
  '<b>Acrolein</b>', 
  '<b>Acrylonitrile</b>',
  '<b>Ammonia</b>',
  '<b>Aniline</b>',
  '<b>Arsenic</b>',
  '<b>Arsine</b>',
  '<b>Butadiene</b>',
  '<b>Barium</b>',
  '<b>Benzene</b>',
  '<b>Blister Agent-Nitrogen Mustard</b>',
  '<b>Blister Agent-Lewisite</b>',
  '<b>Blister Agent-Sulful Mustard</b>',
  '<b>Bromomethene</b>',
  '<b>Calcium/Sodium Hypochlorite</b>',
  '<b>Carbon Disulfide</b>',
  '<b>Chlordane</b>',
  '<b>Chlorine</b>',
  '<b>Crotonaldehyde</b>',
  '<b>Cyanide</b>',
  '<b>Dibromoethane</b>',
  '<b>Dioxane</b>',
  '<b>Diborane</b>',
  '<b>Dichlorobenzene-1,4</b>',
  '<b>Dichlorobenzene-1,3</b>',
  '<b>Dichlorobenzene-1,2</b>',
  '<b>Ethylene Dibromide</b>',
  '<b>Ethylene Glycol</b>',
  '<b>Ethylene Oxide</b>',
  '<b>Fluorides</b>',
  '<b>Formaldehyde</b>',
  '<b>Gasoline (Petrol/Diesel/Others)</b>',
  '<b>Heptachlor</b>',
  '<b>Hydrogen Chloride</b>',
  '<b>Hydrogen Cyanide</b>',
  '<b>Hydrogen Fluoride</b>',
  '<b>Hydrogen Peroxide</b>',
  '<b>Hydrogen Sulfide</b>',
  '<b>Lead</b>',
  '<b>Malathion</b>',
  '<b>Mercury</b>',
  '<b>Methyl Isocyanate</b>',
  '<b>Methyl Mercaptan</b>',
  '<b>Methylene Chloride</b>',
  '<b>Nerve Agents (Tabun, Sarin, Soman, Vx)</b>',
  '<b>Nitrogen Oxides</b>',
  '<b>Parathion</b>',
  '<b>Phenol</b>',
  '<b>Phosgene</b>',
  '<b>Phosgene Oxime</b>',
  '<b>Phosphine(Aluminum/ZnPhosphide)</b>',
  '<b>Trichloroethane</b>',
  '<b>Tetrachloroethylene</b>',
  '<b>Toluene</b>',
  '<b>Toluene Diisocyanate</b>',
  '<b>Trichloroethylene</b>',
  '<b>Unidentified Chemical</b>',
  '<b>Vinyl Chloride</b>',
  '<b>Xylene</b>',
  '<a href="https://www.atsdr.cdc.gov/MHMI/mmg124.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg125.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg126.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg171.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg2.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg169.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg28.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg24.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg3.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg164.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg163.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg165.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg27.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg184.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg82.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg31.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg172.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg180.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg8.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg37.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg187.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg181.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg10c.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg10b.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg10a.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg37.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg96.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg137.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg11.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg111.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg72.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg12.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg173.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg8.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg11.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg174.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg114.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg13.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg154.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg46.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg182.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg139.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg14.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg166.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg175.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg48.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg115.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg176.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg167.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg177.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg70.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg18.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg56.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg179.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg19.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MMG/MMG.asp?id=1138&tid=243" target="_blank">Open</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg20.pdf" target="_blank">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg71.pdf" target="_blank">Download'
),58)
colnames(m) = c('<span style="color:red">Name of the Toxic Substance</span>', '<span style="color:blueviolet">PDF</span>')

ui <- fluidPage(
  titlePanel(h2("Medical Management Guidelines for Toxic Substances",style = "color:blue")),
  h4("Design and Development: Dr. Arkaprabha Sau, MBBS, MD(Gold Medalist), DPH ",style="color:darkmagenta"),
  h4("Reference: Agency for Toxic Substances and Disease Registry,CDC,Atlanta,USA",style="color:green"),
  br(),
  DT::dataTableOutput("mytable")
)

server <- function(input, output) {
  output$mytable = DT::renderDataTable({
    m
  },escape=FALSE)
}

shinyApp(ui, server)
