m = matrix(c(
  '<b>Acrolein</b>', 
  '<b>Acrylonitrile</b>',
  '<b>Ammonia</b>',
  '<b>Aniline</b>',
  '<b>Arsenic</b>',
  '<b>Arsine</b>',
  '<b>Butadiene</b>',
  '<b>Barium</b>',
  '<b>Benzene</b>',
  '<b>Blister Agent-Nitrogen Mustard</b>',
  '<b>Blister Agent-Lewisite</b>',
  '<b>Blister Agent-Sulful Mustard</b>',
  '<b>Bromomethene</b>',
  '<b>Calcium/Sodium Hypochlorite</b>',
  '<b>Carbon Disulfide</b>',
  '<b>Chlordane</b>',
  '<b>Chlorine</b>',
  '<b>Crotonaldehyde</b>',
  '<b>Cyanide</b>',
  '<b>Dibromoethane</b>',
  '<b>Dioxane</b>',
  '<b>Diborane</b>',
  '<b>Dichlorobenzene-1,4</b>',
  '<b>Dichlorobenzene-1,3</b>',
  '<b>Dichlorobenzene-1,2</b>',
  '<b>Ethylene Dibromide</b>',
  '<b>Ethylene Glycol</b>',
  '<b>Ethylene Oxide</b>',
  '<b>Fluorides</b>',
  '<b>Formaldehyde</b>',
  '<b>Gasoline (Petrol/Diesel/Others)</b>',
  '<b>Heptachlor</b>',
  '<b>Hydrogen Chloride</b>',
  '<b>Hydrogen Cyanide</b>',
  '<b>Hydrogen Fluoride</b>',
  '<b>Hydrogen Peroxide</b>',
  '<b>Hydrogen Sulfide</b>',
  '<b>Lead</b>',
  '<b>Malathion</b>',
  '<b>Mercury</b>',
  '<b>Methyl Isocyanate</b>',
  '<b>Methyl Mercaptan</b>',
  '<b>Methylene Chloride</b>',
  '<b>Nerve Agents (Tabun, Sarin, Soman, Vx)</b>',
  '<b>Nitrogen Oxides</b>',
  '<b>Parathion</b>',
  '<b>Phenol</b>',
  '<b>Phosgene</b>',
  '<b>Phosgene Oxime</b>',
  '<b>Phosphine(Aluminum/ZnPhosphide)</b>',
  '<b>Trichloroethane</b>',
  '<b>Tetrachloroethylene</b>',
  '<b>Toluene</b>',
  '<b>Toluene Diisocyanate</b>',
  '<b>Trichloroethylene</b>',
  '<b>Unidentified Chemical</b>',
  '<b>Vinyl Chloride</b>',
  '<b>Xylene</b>',
  '<a href="https://www.atsdr.cdc.gov/MHMI/mmg124.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg125.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg126.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg171.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg2.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg169.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg28.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg24.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg3.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg164.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg163.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg165.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg27.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg184.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg82.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg31.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg172.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg180.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg8.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg37.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg187.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg181.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg10c.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg10b.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg10a.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg37.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg96.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg137.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg11.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg111.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg72.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg12.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg173.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg8.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg11.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg174.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg114.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg13.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg154.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg46.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg182.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg139.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg14.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg166.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg175.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg48.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg115.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg176.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg167.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg177.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg70.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg18.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg56.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg179.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg19.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MMG/MMG.asp?id=1138&tid=243">Open</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg20.pdf">Download</a>',
  '<a href="http://www.atsdr.cdc.gov/MHMI/mmg71.pdf">Download'
  ),58)
colnames(m) = c('<span style="color:red">Name of the Toxic Substance</span>', '<span style="color:blueviolet">PDF (Please wait for 6 to 7 second after clicking Download)</span>')
datatable(m)
#m1=datatable(m,escape = F)
